# Generated by Django 5.2.15 on 2026-06-11 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID from the source dataset.')),
                ('name', models.CharField(help_text='Commercial name of the truckstop.', max_length=255)),
                ('address', models.CharField(help_text='Street address / highway exit info.', max_length=500)),
                ('city', models.CharField(help_text='City where the station is located.', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='Two-letter US state abbreviation.', max_length=2)),
                ('rack_id', models.IntegerField(help_text='Rack pricing region identifier.')),
                ('retail_price', models.FloatField(help_text='Retail price per gallon in USD.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('latitude', models.FloatField(blank=True, db_index=True, help_text='Geographic latitude (WGS84).', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, db_index=True, help_text='Geographic longitude (WGS84).', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_station_coords'), models.Index(fields=['state', 'retail_price'], name='idx_state_price')],
            },
        ),
    ]
